[package]
name = "oblast"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"
description = "High-level wrapper for blst"

[dependencies]
hex = "0.4.2"
paste = "1.0.4"
blst = "0.3.10"
num-bigint = "0.3.1"